server:
  servlet:
    context-path: /test
  tomcat:
    basedir: tomcat
    accesslog:
      enabled: true
      directory: log
      pattern: '%h %l %u %t %r %s %b'
      max-days: 30
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.128:5432/adssodb
    username: postgres
    password: postgres
  data:
    redis:
      port: 6379
      host: 192.168.88.128
      password:
      database: 0

logging:
  file:
    name: ./logs/ap.log